apiVersion: v1
kind: Service
metadata:
  name: spring-webflux-todolist-node-port
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31388
  selector:
    component: spring-webflux-todolist
